config/routes.rb
Rails.application.routes.draw do
  root 'sessions#login'

  #user
  resources :users, only: [:new, :create, :destroy] #dont need destroy yet

  #session
  get '/login', to: 'sessions#login'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  post '/logout', to: 'sessions#destroy'

  #main
  resources :notes
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :require_login
  include ApplicationHelper

  def index
    @notes = Note.where(user_id: session[:user_id])
    #puts "User ID: #{session[:user_id]}"
    #puts "Current User ID: #{@current_user}"
    #puts "Number of Notes: #{@notes.count}"
  end

  def new
    @note = Note.new
  end

  def create
    @note = Note.new(note_params)
    if @note.save
      redirect_to notes_path
    else
      render :new
    end
  end

  private

  def note_params
    params.require(:note).permit(:user_id, :title, :text)
  end

  private def require_login
    unless logged_in()
      flash[:danger] = 'Sie waren nicht angemeldet!'
      redirect_to login_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_by(username: params[:username])

    if !!@user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to notes_path
    else
      redirect_to login_path, notice:  "Etwas ist schiefgelaufen! Passwort und Nutzername überprüfen."
    end
  end

  def destroy
    session.delete(:user_id)
    session[:user_id] = nil
    @user = nil
    redirect_to root_path
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  private def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def logged_in
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyPassword</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/index.html.erb
<h1>Notizen</h1>
<p>
  <%= link_to 'Abmelden', logout_path %>
  <br>
  <%= link_to 'Neue Notiz', new_note_url %>
</p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Text</th>
    </tr>
  </thead>
  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.title %></td>
        <td><%= note.text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/notes/new.html.erb
<h1>Neue Notiz</h1>
<div>
  <%= form_for @note do |f| %>
    <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_area :text %>
      <%= f.submit 'Neue Notiz' %>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Neuer User</h1>
<div>
  <%= form_for @user do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <%= f.submit "Neuer Account" %>
    <p>Schon Registriert? <%= link_to 'Anmeldung', root_path %></p>
    <% end %>
</div>